
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GetWellWebApplication.Models
{

using System;
    using System.Collections.Generic;
    
public partial class medecin
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public medecin()
    {

        this.categorie = new HashSet<categorie>();

        this.certificat = new HashSet<certificat>();

        this.diagnostique = new HashSet<diagnostique>();

        this.nootation = new HashSet<nootation>();

        this.rendezvous = new HashSet<rendezvous>();

        this.teleconsultation = new HashSet<teleconsultation>();

    }


    public int Id_doc { get; set; }

    public string Username { get; set; }

    public string Nom { get; set; }

    public string Prenom { get; set; }

    public string Tel { get; set; }

    public byte[] Image { get; set; }

    public string Email { get; set; }

    public Nullable<int> Nbrpatients { get; set; }

    public string ville { get; set; }

    public string Adresse { get; set; }

    public string Facebook { get; set; }

    public string Whatsapp { get; set; }

    public string Instagram { get; set; }

    public string Twitter { get; set; }

    public string Linkeden { get; set; }

    public string password { get; set; }

    public Nullable<System.Guid> salt { get; set; }

    public Nullable<double> latitude { get; set; }

    public Nullable<double> longitude { get; set; }

    public string cin { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<categorie> categorie { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<certificat> certificat { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<diagnostique> diagnostique { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<nootation> nootation { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<rendezvous> rendezvous { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<teleconsultation> teleconsultation { get; set; }

}

}
