
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GetWellWebApplication.Models
{

using System;
    using System.Collections.Generic;
    
public partial class patient
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public patient()
    {

        this.diagnostique = new HashSet<diagnostique>();

        this.nootation = new HashSet<nootation>();

        this.rendezvous = new HashSet<rendezvous>();

        this.teleconsultation = new HashSet<teleconsultation>();

    }


    public int Id_patient { get; set; }

    public string CIN { get; set; }

    public string Nom { get; set; }

    public string Prenom { get; set; }

    public Nullable<System.DateTime> Date_naissance { get; set; }

    public string Tel { get; set; }

    public string Email { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<diagnostique> diagnostique { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<nootation> nootation { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<rendezvous> rendezvous { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<teleconsultation> teleconsultation { get; set; }

}

}
